### ISSUE TITLE
MoParser fails when you need to make use of context translation (_dx function)

### ISSUE THREAD

**Issue by iliepandia** [cakephp/cakephp#10453]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.0
* Platform and Target: Apache 2.16, Php 5.6, MySQL

### What you did
I am using the function __dx() like so:

`__dx('meetings', 'speaking time', 'Time')`

And somewhere else in the code I use

`__d('meetings','Time')`

### What happened
When Cake MoParser tries to load the translation and gets to this part it crashes with the exception:

Error: Cannot use string offset as an array 
File [...]\vendor\cakephp\cakephp\src\I18n\Parser\MoFileParser.php 
Line: 130

### What you expected to happen
I expect that the .mo file parsed correctly and w/o errors. 

Seems like using "Time" once with context and then w/o context does not go well with the parser.

**Comment by maxmasetti** [comment]
I have a similar problem with mo file compiled by poedit and context translations, by example I have 
```
<?= __x('Classrooms', 'All') ?>
```
which makes CakePHP fail with:
```
Warning (2): Illegal string offset '_context' [CORE/src/I18n/Parser/MoFileParser.php, line 130]
Fatal error: Cannot use string offset as an array in /Users/.../vendor/cakephp/cakephp/src/I18n/Parser/MoFileParser.php on line 130
Warning (2): Illegal string offset '_context' [CORE/src/I18n/Parser/MoFileParser.php, line 130]
Fatal error: Cannot use string offset as an array in /Users/.../vendor/cakephp/cakephp/src/I18n/Parser/MoFileParser.php on line 130
```

thanks

**Comment by iliepandia** [comment]
@maxmasetti do you have in the code a call like
`__('All')`

**Comment by maxmasetti** [comment]
yes, I do.
And w/o the mo, it "works" but the translation is wrong, i.e. as for __('All').
This is a problem, isn't it?
What do you adivice?
thx

**Comment by markstory** [comment]
Please upgrade your version of CakePHP.  This sounds very similar to #10004

**Comment by dereuromark** [comment]
This is fixed in 3.3.12 - after upgrading the issue should be gone then as outlined.

**Comment by jeannunes** [comment]
I'm on 3.4 and I'm still getting this problem.

Do you have any ideia on how to fix it?

**Comment by rrd108** [comment]
I run into the same with CakePHP 3.6.10

**Comment by ADmad** [comment]
Please open a new issue with proper details instead of commenting on a closed issue.
