### ISSUE TITLE
__d() doesn't take the correct msgstr depending on the position of the msgstr inside the .po file

### ISSUE THREAD

**Issue by burzum** [cakephp/cakephp#10730]
Copy pasting the internal ticket from my workmate @antoniosergio-moreira here. @netstyler

---

### Original Problem
In the website's - www.german-architects.com -  main navigation and in the Profiles navigation, the translation for the word "Projects" is only displaying "Projekt" and not "Projekte" (plural)

![bildschirmfoto-2017-06-06-um-15 22 17](https://cloud.githubusercontent.com/assets/13075805/26831430/8cba086a-4acc-11e7-817b-cb191fc174ea.jpg)

### What we did at first
We checked the .po file for the word "Projects" and did not find anything. That was issue n.1. Issue n.2 is a bit trickier. 

in `src/View/Helper/ProfileHelper.php`, line 75

```
[
	'name' => __d('wa', 'Projects'),
	'link' => ['controller' => 'Profiles', 'action' => 'view', $profile->slug, 'projects'],
	'editLink' => ['controller' => 'Profiles', 'action' => 'edit', 'projects'],
	'counterField' => 'project_count',
],
```

We added this word - "Projects" -  as a msgstr to the `src/Locale/de/wa.po`file. 
At first, we added it in lines 297-298. Note that in lines 306-309 there is the singular/plural translation for Project/Projects. Having done this and cleared the cache, we note that the translations are not working in the website. 

**Addind the msgstr in lines 297-298**
![screen shot 2017-06-07 at 10 16 00](https://user-images.githubusercontent.com/8680933/26868754-5ab27502-4b6a-11e7-9a4f-259531c85b78.png)
**In the website, translations are not accurate**
![screen shot 2017-06-07 at 10 17 38](https://user-images.githubusercontent.com/8680933/26868849-9c3dc5e4-4b6a-11e7-9ab4-656f3400c4e7.png)

### What we did afterwards
Afterwards, we moved the msgstrs to the bottom of the `src/Locale/de/wa.po` file (lines 1934-1935). After clearing cache once again, we note that the translations in the frontend are now correct. 
**Addind the msgstr in lines 1935-1936**
![screen shot 2017-06-07 at 10 29 59](https://user-images.githubusercontent.com/8680933/26869329-5679baac-4b6c-11e7-80f2-6f36e1733193.png)
**In the website, translations are accurate**
![screen shot 2017-06-07 at 10 20 31](https://user-images.githubusercontent.com/8680933/26869050-4d9a26de-4b6b-11e7-8f78-77c7cd30bbea.png)

Seems it has something to do with the fact that **if** the msgstr are set **before** the singular/plural strings, this causes an issue - the msgstr isn't triggered or active or whatever the hell  - and if the msgstr is set **after** the singular/plural strings, then all is well and everyone is smiling and happy and depression-free.

**Comment by dereuromark** [comment]
Is this related to https://github.com/cakephp/cakephp/pull/10597 ? Does the PR also fix this, or are those separate issues?

**Comment by burzum** [comment]
@dereuromark I haven't tested the PR but after reading the issues comment history I think this pretty much is the same.

**Comment by markstory** [comment]
There have been a few po file parsing changes since this was reported. Is this still an issue.

**Comment by markstory** [comment]
Fixed in #11127

**Comment by burzum** [comment]
@markstory this is still an issue as reported today by @netstyler CakePHP 3.5.5.

**Comment by netstyler** [comment]
If I remove :
```
msgid "Project"
msgid_plural "Projects"
msgstr[0] "Projekt"
msgstr[1] "Projekte"
```

Then the following does take effect:

```
msgid "Projects"
msgstr "Projekte"
```

It shows then the plural version.
It does not matter in which order I set the plural translations. Before or after the normal translations.
The plural translation seam to overwrite the normal `msgid "Projects"` translations.

**Comment by burzum** [comment]
@markstory I've added a test in a new branch https://github.com/cakephp/cakephp/tree/bug/plural-issues Check it out and run `vendor\bin\phpunit tests\TestCase\I18n\Parser\PoFileParserTest.php` to see the problem.

**Comment by markstory** [comment]
The message parsed on L115 *is* singular as it is a *single* message without plural forms attached. The parser can't look at the contents of message ids to guess whether they are singular or plural values.
