### ISSUE TITLE
Cache groups are not working

### ISSUE THREAD

**Issue by segy** [cakephp/cakephp#5894]
I suppose cache groups are not working as they should. I have this configuration:

```php
$defaultCache = [
    'className' => 'File',
    'path' => CACHE . 'plugin' . DS,
    'probability' => 100,
    'duration' => '+1 year'
];

// cache definitions
Cache::config('plugin_language', array_merge($defaultCache, [
    'groups' => ['Languages']
]));
Cache::config('plugin_configuration', array_merge($defaultCache, [
    'groups' => ['Configurations']
]));
```

When I try to remove Languages group by calling:

```php
foreach (Cache::groupConfigs('Languages') as $config) {
    Cache::clearGroup('Languages', $config);
}
```

I get the exception *Invalid cache group Languages*

It is thrown in *\Cake\Cache\Cache groupConfigs* method and when I *var_dump(static::$_groups);* there, it is an empty array.

**Comment by markstory** [comment]
What version of CakePHP are you using? Cache groups should be working as there are passing tests for them.

**Comment by segy** [comment]
I updated now - `Updating cakephp/cakephp 3.0.x-dev (9bae44e => 2091c68)`

But still getting *Invalid cache group* exception

**Comment by segy** [comment]
I figured it out when I checked tests for Cache groups. Before groupConfigs is called, there is always called `$engine = Cache::engine('...');`.

When I add this, it works also for me. Question is, when should this be called (if right after Cache::config). I suggest adding this method to caching book page.

**Comment by markstory** [comment]
Ok, I can take a look.

**Comment by markstory** [comment]
Closing as #5906 will fix this.

**Comment by segy** [comment]
thank you

**Comment by mirorac** [comment]
I still get the _Invalid cache group_ exception. (updated to 3.2.1 stable few minutes ago)

IMO the problem is that at Cake/Cache/Cache.php:156 the if statement checks `$config['groups']` which is not present anymore after engines are built. There is only `$config['className']` with engine instance.

This is my workaround (but I think it can be done prettier)
```php
        if(!isset($config['groups']) && is_object($config['className'])){
            $config['groups'] = (array)$config['className']->config('groups'); 
        }
```

added these three lines before `if (!empty($config['groups'])) {` on line 155

_Thanks for your reply_
