### ISSUE TITLE
3.0 patchEntity association fails to preserve request _joinData

### ISSUE THREAD

**Issue by cautionbug** [cakephp/cakephp#6100]
i've been trying for almost a month on this thread https://groups.google.com/forum/#!topic/cake-php/Tuz9T7hO3eg to get a clear answer, but haven't made much progress. i'm hoping by trying it here, some discussion can help clarify if i'm doing something wrong, or there's an untested scenario & possible bug in the ORM.

@markstory was on the IRC channel last week & there was a brief conversation about saving a primary record with a BTM association, and `_joinData` in the middle. The documentation & tests provide these scenarios:

1. When you're saving the primary record (`Articles`, for instance) you're also saving new `Tags`, and adding `_joinData` (`rating`, maybe a nested association to `User`, etc.). 
2. You can retrieve an *existing* `Articles` entity and patch it plus the association `Tags` and the `_joinData`.

Per the discussion last week with Mark, there might be something missing for this scenario:

i have `Tags` already saved. i don't want to change any of them or create new when i work on `Articles`. i want to pick from the existing `Tags`, and save some `_joinData` in the pivot table. All i should need from `Tags` is the ID so i can create the linking record with `article_id`, `tag_id`, and the additional data.

My POST data looks like the documentation says it should:
```php
[
// ... Some fields for the primary Article entity, then...
    tags => [
        3 => [ // This is the form input index for Tags, not an ID
            id => 1, // The Tag ID
            _joinData => [
                value => Save me! // Yes, value is the column name
            ]
        ]
    ]
]
```
In my Controller:
```php
$article = $this->Articles->newEntity();
if ($this->request->is('post')) {
    $article = $this->Articles->patchEntity($article, $this->request->data, 
                                            ['associated' => ['Tags._joinData']]);
    if ($this->Articles->save($article)) {
        // rejoice!
    }
}
```
The patched Entity looks like:
```json
{
    "...": "Fields for the primary Article entity, then...",
    "tags": [
        {
            "id": 1,
            "...": "Other fields for the Tags entity"
        }
    ]
}
```
i Logged `$article->errors()` on the patched entity and got NOTHING, so everything checks out, right? But where is the `_joinData`???

After the save *SUCCEEDS*, the updated entity looks like:
```json
{
    "...": "Fields for the Article entity, then...",
    "tags": [
        {
            "id": 1, 
            "...": "Other fields for Tag entity, then...",
            "_joinData": {
                "id": 13,
                "article_id": 14,
                "tag_id": 1
             }
        }
    ]
}
```
Wait, WHAT? Yes, the `Tags` entity is now looking up the existing Tag (thanks to PR #6086, i think), and it's generating the linking record (`_joinData`). But because `value` wasn't preserved during `patchEntity()`, the column in that record is `NULL`.

Table classes (per http://book.cakephp.org/3.0/en/orm/associations.html#using-the-through-option):
```php
class ArticleTable extends Table {
    public function initialize(array $config) {
        // ... displayField, addBehavior, other relationships...
        $this->belongsToMany('Tags', [
            'through' => 'ArticlesTags'
        ]);
    }
    public function validationDefault(Validator $validator) {
        // Everything is exactly as the bake command wrote it.
    }
    public function buildRules(RulesChecker $rules) {
        // Everything is exactly as the bake command wrote it.
    }
}

class TagsTable extends Table {
    public function initialize(array $config) {
        // table, primaryKey, displayField, etc...
        $this->belongsToMany('Articles', [
            'through' => 'ArticlesTags'
        ]); 
    }
    public function validationDefault(Validator $validator) {
        // All validation commented out, per discussion with @markstory
    }
}

class ArticleTagsTable extends Table {
    public function initialize(array $config) {
        $this->belongsTo('Articles');
        $this->belongsTo('Tags');
    }
    public function validationDefault(Validator $validator) {
        $validator
        // Typical validation as written by bake, then...
            ->requirePresence('value', 'create')
            ->allowEmpty('value')
            ->allowEmpty('article_id', 'create')
            ->allowEmpty('tag_id', 'create')
    }
    public function buildRules(RulesChecker $rules) {
        $rules->add($rules->existsIn(['article_id'], 'Articles'));
        $rules->add($rules->existsIn(['tag_id'], 'Tags'));
        return $rules;
    }
}
```

i *hoped* PR #6086 would address this problem, but after updating to the current HEAD, it's not happening. i'm stumped. i managed to get a different approach to work, using `$this->Articles->Tags->link()`, but i listed several reasons i really want to avoid using that in the Google Group thread.

Can someone help? i haven't managed to be on IRC when Mark is around to explore this further, and if it's a bug, it would be great to get a fix for it. If it's something i didn't do correctly to my Table or Entity classes, i'll make changes, but i suggest the issue stands as a documentation problem, since i've left those classes virtually untouched since **bake** wrote them. Changes i made were to use the `'through'` option (per docs), and disabling validations as requested during conversation.

Thanks everyone.

**Comment by markstory** [comment]
Thanks for the extra context. I can try and reproduce this in the testsuite and seeif we can get a solution, as what you're describing should work.

**Comment by cautionbug** [comment]
Thanks for looking into it. i have some variations on my laptop that i tried while we were talking on IRC (none worked at the time), but i'll try them against the current HEAD to see if there's any difference. One variation involved adding `$_accessible['_joinData']` to one of the Entities, but i don't remember which at the moment. It didn't work then, but i'll try again.

**Comment by markstory** [comment]
I tried to reproduce this in the test suite and didn't have much luck. I tried adding the following test

```php
    /**
     * Test merging belongsToMany data doesn't create 'new' entities.
     *
     * @return void
     */
    public function testMergeBelongsToManyJoinDataAssociatedWithIds()
    {
        $data = [
            'title' => 'My title',
            'tags' => [
                [
                    'id' => 1,
                    '_joinData' => [
                        'active' => 1,
                        'user' => ['username' => 'MyLux'],
                    ]
                ],
                [
                    'id' => 2,
                    '_joinData' => [
                        'active' => 0,
                        'user' => ['username' => 'IronFall'],
                    ]
                ],
            ],
        ];
        $articlesTags = TableRegistry::get('ArticlesTags');
        $articlesTags->belongsTo('Users');

        $marshall = new Marshaller($this->articles);
        $article = $this->articles->get(1, ['associated' => 'Tags']);
        $result = $marshall->merge($article, $data, ['associated' => ['Tags._joinData.Users']]);

        $this->assertInstanceOf('Cake\ORM\Entity', $result->tags[0]);
        $this->assertInstanceOf('Cake\ORM\Entity', $result->tags[1]);
        $this->assertInstanceOf('Cake\ORM\Entity', $result->tags[0]->_joinData->user);

        $this->assertInstanceOf('Cake\ORM\Entity', $result->tags[1]->_joinData->user);
        $this->assertFalse($result->tags[0]->isNew(), 'Should not be new, as id is in db.');
        $this->assertFalse($result->tags[1]->isNew(), 'Should not be new, as id is in db.');
        $this->assertEquals(1, $result->tags[0]->id);
        $this->assertEquals(2, $result->tags[1]->id);

        $this->assertEquals(1, $result->tags[0]->_joinData->active);
        $this->assertEquals(0, $result->tags[1]->_joinData->active);

        $this->assertEquals(
            $data['tags'][0]['_joinData']['user']['username'],
            $result->tags[0]->_joinData->user->username
        );
        $this->assertEquals(
            $data['tags'][1]['_joinData']['user']['username'],
            $result->tags[1]->_joinData->user->username
        );
    }
```
This test is currently passing. What isn't the same as your situation?

**Comment by markstory** [comment]
I also tried to reproduce this in a test application and wasn't able to make it happen. This [gist](https://gist.github.com/markstory/eb0c170b7852ee20d770) has the code I used.

**Comment by cautionbug** [comment]
In the request data, the only difference i can see is my single `tags` sub-array has a numeric "key" corresponding to the array index from the form tying the inputs together, where yours is created raw, so has natural indexes.

Aside from that, there are some small discrepancies between stuff in your gist and my code. For instance i noticed i'm using `'through'` without the other keys, as i assumed convention defaults would handle those. Maybe i'm wrong about that, or mistaken about the convention. i'll specify them to make sure. Your gist's `add` action doesn't save :open_mouth: but otherwise the entity manipulation is exactly the same. Also, if `'_joinData'` is *required* in the `$_accessible` array for this process, can you make sure it's noted in the Docs at: http://book.cakephp.org/3.0/en/orm/saving-data.html#saving-additional-data-to-the-joint-table

i'll work on it tonight after work & follow up.

**Comment by markstory** [comment]
@cautionbug The data I have is numerically indexed as well, it just starts at 0. I can try starting at non-zero too.  The controller action intentionally doesn't save as you mentioned the issues was that the hydrated entities were incorrect.

The `_joinData` key _should_ be in _accessible if it is not, however that isn't required as the _joinData is not 'mass assigned'.

**Comment by cautionbug** [comment]
@markstory AHA!!!!!!

It's the POST array index on the associated data!

Here's what i did:  
1. Aligned all my code to look like yours. Added what was missing from Entities & so on.
2. Didn't get *anything* different.
3. Last-ditch effort, i did this:
```php
$article = $this->Articles->newEntity();
if ($this->request->is('post')) {
    // Reset indexes on the associated data 
    // (see the original POST data above, it didn't change at all)
    $this->request->data['tags'] = array_values($this->request->data['tags']);

    $article = $this->Articles->patchEntity($article, $this->request->data,
                                            ['associated' => ['Tags._joinData']]);
    $this->Articles->save($article);
}
```

Guess what. Go on. Guess. i have no explanation, but only when the associated data is 0-indexed did it finally save *with* the `_joinData`. i went back and attempted 2 Tags, one that requires a `[value]` in the pivot record, the other doesn't. Both saved successfully.

i'm willing to use this work-around for now, but would really like to understand what's going on. Since the non-0 indexes are due to the counter (`tags.0.id`, `tags.0._joinData.starred`), do you have any suggestions for submitting the data with "clean" indexes? Or should this be addressed in the ORM so the indexes/keys of the associated data don't actually matter? i mean, if you look at my sample POST data, the number 3 isn't USED for anything, it just keeps the `tag ID` input and its `_joinData` input(s) tied together.

Thoughts?

**Comment by markstory** [comment]
Interesting. I will look into why a zero based array is required currently.

**Comment by cautionbug** [comment]
Assuming the Table/Entiity classes weren't the cause of the problem, the pivot record wasn't saving at all before PR #6086 when it started partially working, just no `_joinData`. So it *appears* the index is only problematic there. But i'm obviously no expert.

Thanks for your help with working on this & figuring it out.

**Comment by markstory** [comment]
Fixed with #6133.

**Comment by cautionbug** [comment]
Thank you!

**Comment by mauricabrera** [comment]
I need some help! I still have the _join data forgotten even after i put this before patch Entity        $this->request->data['products'] = array_values($this->request->data['products']);

Can you help me please?? Its really weird, beacuse when i choose only the first product with its respective quantity as my case, it works! but when i choose more products the _joinData goes null! PLEASE HELP! im in this problem for days!!

**Comment by mauricabrera** [comment]
This is my add function and its add.ctp form Im following the google group and this repository so you know how my other baked entities tables controllers are
```
public function add()
    {
        $sobre = $this->Sobres->newEntity();
        if ($this->request->is('post')) {
            // Reset indexes on the associated data 
    
    $this->request->data['products'] = array_values($this->request->data['products']);

    $sobre = $this->Sobres->patchEntity($sobre, $this->request->data,
                                            ['associated' => ['Products._joinData']]);
//        	$sobre = $this->Sobres->patchEntity($sobre, $this->request->data,['associated'=>['products._joinData']]);
//            $sobre->dirty('products._joinData',true);
            if ($this->Sobres->save($sobre)) {
                $this->Flash->success('The sobre has been saved.');
//                return $this->redirect(['action' => 'index']);
            } else {
                $this->Flash->error('The listing could not be saved. Please, try again.');
            }
        }
        $users = $this->Sobres->Users->find('list');
        $clients = $this->Sobres->Clients->find('list');
        $products = $this->Sobres->Products->find('list');
        $this->set(compact('sobre', 'users', 'clients', 'products'));
        $this->set('_serialize', ['sobre']);
    }
```
```
<div class="sobres form large-10 medium-9 columns">
    <?= $this->Form->create($sobre); ?>
    <fieldset>
        <legend><?= __('Add Sobre') ?></legend>
        <?php


             echo $this->Form->input('user_id', ['options' => $users]);
            echo $this->Form->input('client_id', ['options' => $clients]);
            echo $this->Form->input('total');
            
            if(!empty($products)){
            	$i =0;
            	foreach( $products as $k => $pro){
  							echo $this->Form->input('products.'.$i.'.id',['type'=>'checkbox','value'=>$k,'label'=>$pro]); 
                            echo $this->Form->input('products.'.$i.'._joinData.quantity'); 
//  							echo $this->Form->input('products.'.$i.'.name',['type'=>'hidden','value'=>$pro]);
//                            echo $this->Form->input('products.'.$i.'.price',['type'=>'hidden','value'=>$pro]);
  							$i++;
  						}
						}
            
        
        ?>
    </fieldset>
    <?= $this->Form->button(__('Submit')) ?>
    <?= $this->Form->end() ?>
</div>
```

PLEASE HELP!!!
