### ISSUE TITLE
SQL Error when paginating results from query with $query->bind

### ISSUE THREAD

**Issue by sarrala** [cakephp/cakephp#6384]
I have following query object which returns data as it should:

```php
$query = $this->Users
	->find()
	->contain( $this->getAssociations() )
	->matching('TableB.TableC', function($q) {
		return $q->where(['TableC.time_completed BETWEEN :start AND :end']);
	})
	->bind(':start', new \DateTime(date('Y-m-01')), 'date')
	->bind(':end', new \DateTime(date('Y-m-t')), 'date')
	->distinct(['Users.id']);
```

I got associated data exactly as I wanted it to be but when I give it to paginator it fails to select count for results:

```php
$this->set('data', $this->paginate($query));
$this->set('_serialize', ['data']);
```

It gives following SQL error:
```
Error: SQLSTATE[HY093]: Invalid parameter number: no parameters were bound
SQL Query:
SELECT (COUNT(*)) AS `count` FROM (SELECT Users.id ...
```

Without parameter bindings in query it works without any problems.
Only thing that fails is counting through paginate, it seems that paginate does not bind parameters to underlying PDO statement.

**Comment by icaroscherma** [comment]
I'm not sure if I am saying something wrong or not, but according to [this](http://book.cakephp.org/3.0/en/orm/database-basics.html#binding-values) you were supposed to use ``bindValue()`` instead of ``bind()`` (to keep the arguments the same way that they are, or put brackets on them), and you should also remove the colon from the 1st argument of the functions. In a couple of hours I will try to reproduce the same environment at home and see what I can get to help you. What surprises me is that it works outside the Paginate function.

**Comment by icaroscherma** [comment]
@sarrala 
Sorry about typing that late... but I only had enough time to test this now...

I noticed this thing that is strange for me... have you created ``$this->getAssociations()`` ? Because I couldn't find anything closer in the API or Book other than [this](http://api.cakephp.org/3.0/class-Cake.ORM.Association.html) so the use would be something like ``$this->Association``, and if you are using CakePHP 2.x there is [this](http://api.cakephp.org/2.6/class-Model.html#_getAssociated) but even though, the proper command is ``$this->getAssociated()``.

Maybe in your code is typed in the right way and you mistyped here... or have you copied the code?

**Comment by sarrala** [comment]
@icaroscherma 
`$this->getAssociations()` is just method I use for collecting required associations.
It returns array like this:
```php
[
	'TableB.TableC',
	'TableX',
]
```

In this case it could as well be:
```php
$query = $this->Users
    ->find()
    ->contain( ['TableB.TableC'] )
    ->matching('TableB.TableC', function($q) {
        return $q->where(['TableC.time_completed BETWEEN :start AND :end']);
    })
    ->bind(':start', new \DateTime(date('Y-m-01')), 'date')
    ->bind(':end', new \DateTime(date('Y-m-t')), 'date')
    ->distinct(['Users.id']);
```

**Comment by icaroscherma** [comment]
@sarrala 
Have you tried to change:
```
    ->bind(':start', new \DateTime(date('Y-m-01')), 'date')
    ->bind(':end', new \DateTime(date('Y-m-t')), 'date')
```
to
```
    ->bindValue('start', new \DateTime(date('Y-m-01')), 'date')
    ->bindValue('end', new \DateTime(date('Y-m-t')), 'date')
```
or
```
    ->bind(
        ['start', new \DateTime(date('Y-m-01')), 'date'],
        ['end', new \DateTime(date('Y-m-t')), 'date']
    )
```
Basically changed the ``bind()`` to ``bindValue()`` OR use both in arrays, and removed the collons.
But the strange thing is, it's working when Paginate is not used... By the way I'm still checking the Cake files.

**Comment by icaroscherma** [comment]
@sarrala 

Well, just ignore my previous comment... I tested and without the colon the same error happens even without using the Paginate. The ``bindValue`` is not working for me (uknown method error) either... I'm looking deeper into the Paginate to see what I can find, seems to be it is missing a proper ``bind()`` link. And the documentation is missing the colon as you've put in your example and it's the only way that worked for me.

**Comment by icaroscherma** [comment]
Well, debugging the problem, I found that the problem is in the file ``cakephp/src/Controller/Component/PaginatorComponent.php`` around line ``170``: ``$count = $numResults ? $query->count() : 0;``. Seems that the ``count()`` can`t handle properly the bind values.... I'm checking [this](http://api.cakephp.org/3.0/source-class-Cake.ORM.Query.html#492-527) right now.

**Comment by markstory** [comment]
Sounds like Query::cleanCopy() is losing some state when the query is cloned.

**Comment by icaroscherma** [comment]
@markstory 
I'm throwing ``die(print_r())`` and checking where it loses the ``$params``, and seems to be in both files, as I cited before (in my edited comment).

**Comment by icaroscherma** [comment]
@sarrala @markstory 
Guys, I think I found one solution...

``cakephp/src/Controller/Component/PaginatorComponent.php``
```
line 169
-    $results = $query->all();
+    $results = $query;
```

``cakephp/src/ORM/Query.php``
```
after line 520, add this:
                ->valueBinder($this->valueBinder())

the ELSE should be like:
        {
            $statement = $this->connection()->newQuery()
                ->select($count)
                ->from(['count_source' => $query])
                ->valueBinder($this->valueBinder())
                ->execute();
        }
```

I'm not sure if I'm breaking something with this, but I hope that this helps. I tested with and without using bind and both ways worked for me.
BTW, I'm still testing if I can improve the ``PaginatorComponent`` code that I changed.

**Comment by markstory** [comment]
Fixed with #6412

**Comment by tstackhouse** [comment]
It looks like this is actually still an issue in > 3.4.0, I'm seeing this exact error when using a `Query` that I've applied `bind()` parameters to, it looks like this change was undone in commit 5d094af for #7567.  It's symptomatic of the bind parameters getting lost when the paginator creates its "clean copy" of the query for the count call.

**Comment by markstory** [comment]
@tstackhouse The tests added in #6412 are still passing. Could you open a new issue with steps to reproduce the issue you're having?

**Comment by tstackhouse** [comment]
@markstory I'll see if I can product an isolated test case, but I'm constrained on time for this project. I worked around it by avoiding paginate.  It's possible that it's due to a nested matching clause on my query that also used bound values.
