### ISSUE TITLE
Using DateTime in a find does not work when selecting on external tables' fields

### ISSUE THREAD

**Issue by xandje** [cakephp/cakephp#6975]
Using a DateTime in a condition or a ```where()``` works fine when the field being selected on is in that same Model/Table:

**EventsTable.php**
```
    public function getUpcoming() {
        return $this->find('all', [
            'conditions' => ['Events.date >' => new \DateTime('now')],
            'order' => 'Events.date ASC'
        ]);
    }
```

However, when using it as a value of a condition on a foreign table's field, it refuses to work.

**OtherTable.php**
```
    public function findUpcoming() {
       return $this->find('all', [
            'contain' => ['Events'],
            'conditions' => ['Events.date > ' => new \DateTime('now')]
       ]);
    }
```

I consistently am notified that:
```Warning (4096): Object of class DateTime could not be converted to string [CORE/src/Database/Type.php, line 261]```

Looking at the query, it does indeed return a blank string and isn't entered into the SQL statement. When I change the value of the condition on Events.date to ```date('Y-m-d H:i:s')```, all is well. In addition, when I query on ```Other.date``` (i.e. a date field within the *OtherTable*), I can use DateTime. 

Is this just me, or what gives?

**Comment by lorenzo** [comment]
What version of cakephp are you using and what type of association is Events?

**Comment by xandje** [comment]
My bad. 

I am using CakePHP 3.0.6. The association between the two is that Other belongsTo Events.

**Comment by lorenzo** [comment]
@xandje Have you tried updating to the latest cakephp 3.x?

**Comment by xandje** [comment]
@lorenzo I have now. Nothing changed.

**Comment by lorenzo** [comment]
Well, that was a bug fixed in 3.0.7. So please make 100% sure you updated you cakephp and that it is actually not working before we invest time investigating the issue.

**Comment by xandje** [comment]
I understand @lorenzo. I should have updated prior to opening this issue. 

However, I am currently on 3.0.8 and the issue still stands.

**Comment by lorenzo** [comment]
@xandje Would you like help debug the issue? Please put this line at the beginning of the array and let me know if that helps https://github.com/cakephp/cakephp/blob/master/src/ORM/Query.php#L445

**Comment by xandje** [comment]
I'll help you out debugging the issue.

However, you are talking about adding a contain at the beginning of the find options, yes? This is already the case:
```            'contain' => ['Events'],```

**Comment by lorenzo** [comment]
I'm talking about the line in the core that I linked to

**Comment by xandje** [comment]
I'm sorry, I'm having a hard time understanding exactly what you mean. I have copied the line from the core to the beginning of the find's options array:

```
    public function findUpcoming() {
        $now = new \DateTime('now');
        // $now = date('Y-m-d H:i:s');

        return $this->find('all', [
            'contain' => 'contain',
            'contain' => ['Events'],
            'conditions' => [
                'Events.date > ' => $now
            ]
        ]);
    }
```

Does nothing for the warning. 

Commenting out the second 'contain' (which would override the first, obviously) gives me an error that Other is not related to 'contain'.

**Comment by antograssiot** [comment]
@xandge he was just asking you to move the linked line to the same file but line 438 at the beginning of the $valid array from what I understood

**Comment by xandje** [comment]
That makes more sense, I guess.

Unfortunately, does not help.

**Comment by chinpei215** [comment]
@xandje Did you associate OtherTables with EventsTables as <em>'Others hasMany Events'</em> ? 
If so you cannot filter Events on primary where clause. (Forgive me if I am wrong.)
Perhaps, 'conditions' should be moved into 'Events' array.
```php
public function findUpcoming() {
	return $this->find('all', [
		'contain' => [
			'Events' => [
				'conditions' => [ 'Events.date > ' => new \DateTime('now') ]
			]
		]
	]);
}
```

**Comment by markstory** [comment]
Fixed in #7506
