### ISSUE TITLE
passing options to subqueries on treebehavior finders for proper caching

### ISSUE THREAD

**Issue by urulab** [cakephp/cakephp#7043]
When I try to cache an object using TreeBehavior::find('path'), caching works fine on first query but in subqueries (lazy loading) not. The options array must be passed or extract some keys for use in get().

My call:
```php
$this->categories->find('path', ['for' => $id])->cache('path-' . $id);
```
TreeBehavior.php:
```php
public function findPath(Query $query, array $options)
        $node = $this->_table->get($options['for'], ['fields' => [$left, $right]]);

/*** COULD BE ***/
        //In $options: ['cache' => 'default', 'key' => 'path-x'] or put these 2 indexes on new $_options
        $options += ['fields' => [$left, $right]];
        $node = $this->_table->get($options['for'], $options);

//Same for other finders...
``

**Comment by markstory** [comment]
I don't think this will or should work. If you want to cache the entire tree of operations use Cache:: remember(). Passing the cache option around will get complicated as on each contained operation, the cache key needs to be mutated. I think it is simpler and more explicit if the entire set of operations is stored as one cache key.

**Comment by urulab** [comment]
When I rewrite based in your indications:
```php
$path = Cache::remember('path-' . $id, function () use ($id) {
    return $this->categories->find('path', ['for' => $id]);
});
```
I have: ```Error: You cannot serialize or unserialize PDO instances ```

**Comment by markstory** [comment]
@urulab You should try upgrading to 3.0.9. This issue was fixed there. Alternatively call `all()` on the find before caching.

**Comment by urulab** [comment]
After updating 3.0.8 to 3.0.9 as indicated the issue persist. But is bypassing with all().
Retriving with cache() mehod works fine, the problem persist in Cache::remember.

regards

**Comment by markstory** [comment]
I don't think the fixes in 3.0.9 address queries being serializable as we can't change pdo.
