### ISSUE TITLE
notMatching BTM doesn't filter records

### ISSUE THREAD

**Issue by GuidoHendriks** [cakephp/cakephp#9051]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)
 
* CakePHP Version: 3.2.11
* Platform and Target: Apache/MySQL on OSX (MAMP Pro)

### What you did
I wanted to fetch clients that don't have any post users.

```php
// ClientsTable.php
$this->belongsToMany('PostUsers', [
    'className' => 'Users',
    'foreignKey' => 'client_id',
    'targetForeignKey' => 'user_id',
    'joinTable' => 'clients_users',
);
```

Fetching this using `notMatching()`:

```php
$this->Clients->find()
    ->select(['id'])
    ->notMatching('PostUsers');
```

### Expected Behaviour
Fetching clients that don't have any post users.

### Actual Behaviour
Fetched all clients N times (N=number of rows in `users` table).

The generated SQL query:
```sql
SELECT Clients.id AS `Clients__id`
FROM clients Clients 
LEFT JOIN users PostUsers ON 1 = 1
LEFT JOIN clients_users ClientsUsers ON (Clients.id = (ClientsUsers.client_id) AND PostUsers.id = (ClientsUsers.user_id)) 
WHERE ((ClientsUsers.user_id) IS NULL AND (ClientsUsers.client_id) IS NULL)
GROUP BY Clients.id;
```

It's going wrong because it joins users first, without filtering them by client. It would have to be something like this (verified to work):

```sql
SELECT Clients.id AS `Clients__id` 
FROM clients Clients 
LEFT JOIN clients_users ClientsUsers ON (Clients.id = (ClientsUsers.client_id)) 
LEFT JOIN users PostUsers ON (PostUsers.id = (ClientsUsers.user_id))
WHERE ((ClientsUsers.user_id) IS NULL AND (ClientsUsers.client_id) IS NULL)
```

**Comment by lorenzo** [comment]
This is fixed in 3.3. The current implementation is doing the "right thing" under one of the valid interpretations of the operation. The semantics of the operations have been changed in 3.3 to avoid his surprise your are having today.

Unfortunately this cannot be back ported to 3.2, because your proposed solution actually breaks other use cases of the function.

I good suggest either using a group by as a workaround or upgrading to 3.next. I reckon there should be a stable release soon

**Comment by GuidoHendriks** [comment]
Thanks for quick response.

Group by doesn't solve it, still shows all the clients. The ones with a record in `clients_users` just are repeated less times. So it would only be filtered if a client is linked to all users.

I already solved it by implementing those joins manually. Will have a look at it again once 3.3 is released.

**Comment by lorenzo** [comment]
Well the thing is this.... Those clients should not be filtered, since the semantic of the operation is that the should NOT match the other association. Both clients with in matching users and clients with no users at all should be part of the response.

The problem in question is the repetition, which I'm certain it can be solved using a group by.

Since you already have a working solution, I'm going to close this.

**Comment by GuidoHendriks** [comment]
The fact that I already have a working solution, should be a reason to take this issue more seriously. For my project it doesn't matter if this works or not, it works for me anyway. I'm spending time to contribute here for no other reason than improving CakePHP. I don't appreciate you dismissing this issue without actually looking into it.

I created a [sample project](https://github.com/GuidoHendriks/cakephp-not-matching) based on the [documentation on `notMatching`](http://book.cakephp.org/3.0/en/orm/retrieving-data-and-resultsets.html#using-notmatching). I created migration file for the database scheme and added some queries in the [`TestNotMatchingShell`](https://github.com/GuidoHendriks/cakephp-not-matching/blob/master/src/Shell/TestNotMatchingShell.php).

My conclusion is still: The behaviour of `notMatching` for BTM is unexpected, it doesn't match the other relation types. Grouping it doesn't fix it. Please have a look at the sample project, as I'm sure you'll agree with me on this.

**Comment by lorenzo** [comment]
@GuidoHendriks sorry I sounded rude or dismissing. I did take a look at the issue, it is not the first report and it actually took me 2 months of thinking and pondering what the right solution to it might be. Due to the implications of the solution, I had to target 3.3

You can read the reasoning here:

https://github.com/cakephp/cakephp/pull/9036
